import { Pirata_One, Merriweather } from "next/font/google";
import "./globals.css";

const pirataOne = Pirata_One({ subsets: ["latin"] });
const merriweather = Merriweather({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={``}>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
